version: "3.9"

services:
  web:
    build: .
    container_name: digit_app_web
    ports:
      - "8501:8501"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=digitdb
      - DB_USER=postgres
      - DB_PASSWORD=mysecretpassword
    volumes:
      - ./mnist_model.pt:/app/mnist_model.pt

  db:
    image: postgres:15
    container_name: digit_app_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: digitdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
